
# This file is automatically generated, you probably don't want to edit this

bootPairedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootPairedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pair1 = NULL,
            pair2 = NULL,
            nBoot = 1000,
            ciWidth = 95,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootPaired",
                requiresData=TRUE,
                ...)

            private$..pair1 <- jmvcore::OptionVariable$new(
                "pair1",
                pair1,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..pair2 <- jmvcore::OptionVariable$new(
                "pair2",
                pair2,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..pair1)
            self$.addOption(private$..pair2)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        pair1 = function() private$..pair1$value,
        pair2 = function() private$..pair2$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..pair1 = NA,
        ..pair2 = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootPairedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootPairedResults",
    inherit = jmvcore::Group,
    active = list(
        testTable = function() private$.items[["testTable"]],
        descTable = function() private$.items[["descTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowy PU dla prob zaleznych")
            self$add(jmvcore::Table$new(
                options=options,
                name="testTable",
                title="Bootstrapowy PU dla r\u00F3\u017Cnicy \u015Brednich (pr\u00F3by zale\u017Cne)",
                clearWith=list(
                    "pair1",
                    "pair2",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="meanDiff", 
                        `title`="\u015Arednia r\u00F3\u017Cnic", 
                        `type`="number"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descTable",
                title="Statystyki opisowe",
                clearWith=list(
                    "pair1",
                    "pair2"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Zmienna", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="\u015Arednia", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="Odch. std.", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plots",
                title="Rozk\u0142ad bootstrapowy",
                width=500,
                height=350,
                clearWith=list(
                    "pair1",
                    "pair2",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                renderFun=".plot"))}))

bootPairedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootPairedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootPaired",
                version = c(0,1,0),
                options = options,
                results = bootPairedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowy PU dla prob zaleznych
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowy przedzial ufnosci dla roznicy srednich w probach zaleznych (parowych).
#'}
#' @param data .
#' @param pair1 .
#' @param pair2 .
#' @param nBoot .
#' @param ciWidth .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$testTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$testTable$asDF}
#'
#' \code{as.data.frame(results$testTable)}
#'
#' @export
bootPaired <- function(
    data,
    pair1,
    pair2,
    nBoot = 1000,
    ciWidth = 95,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootPaired requires jmvcore to be installed (restart may be required)")

    if ( ! missing(pair1)) pair1 <- jmvcore::resolveQuo(jmvcore::enquo(pair1))
    if ( ! missing(pair2)) pair2 <- jmvcore::resolveQuo(jmvcore::enquo(pair2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(pair1), pair1, NULL),
            `if`( ! missing(pair2), pair2, NULL))


    options <- bootPairedOptions$new(
        pair1 = pair1,
        pair2 = pair2,
        nBoot = nBoot,
        ciWidth = ciWidth,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootPairedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

