
# This file is automatically generated, you probably don't want to edit this

bootTest2Options <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootTest2Options",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            group1Level = NULL,
            group2Level = NULL,
            nBoot = 1000,
            ciWidth = 95,
            showClassical = FALSE,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootTest2",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..group1Level <- jmvcore::OptionLevel$new(
                "group1Level",
                group1Level,
                variable="(group)")
            private$..group2Level <- jmvcore::OptionLevel$new(
                "group2Level",
                group2Level,
                variable="(group)")
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..showClassical <- jmvcore::OptionBool$new(
                "showClassical",
                showClassical,
                default=FALSE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..group1Level)
            self$.addOption(private$..group2Level)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showClassical)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        group1Level = function() private$..group1Level$value,
        group2Level = function() private$..group2Level$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        showClassical = function() private$..showClassical$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..group1Level = NA,
        ..group2Level = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..showClassical = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootTest2Results <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootTest2Results",
    inherit = jmvcore::Group,
    active = list(
        testTable = function() private$.items[["testTable"]],
        descTable = function() private$.items[["descTable"]],
        classicalTable = function() private$.items[["classicalTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowe porownanie dwoch grup")
            self$add(jmvcore::Table$new(
                options=options,
                name="testTable",
                title="Bootstrapowy PU dla r\u00F3\u017Cnicy \u015Brednich",
                rows="(dep)",
                clearWith=list(
                    "group",
                    "group1Level",
                    "group2Level",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Zmienna", 
                        `type`="text"),
                    list(
                        `name`="meanDiff", 
                        `title`="R\u00F3\u017Cnica \u015Brednich", 
                        `type`="number"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"),
                    list(
                        `name`="n1", 
                        `title`="N (Grupa 1)", 
                        `type`="integer"),
                    list(
                        `name`="n2", 
                        `title`="N (Grupa 2)", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descTable",
                title="Statystyki opisowe",
                clearWith=list(
                    "dep",
                    "group",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Zmienna", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group", 
                        `title`="Grupa", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="\u015Arednia", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="Odch. std.", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="classicalTable",
                title="Test klasyczny (t-test dla dw\u00F3ch pr\u00F3b)",
                visible="(showClassical)",
                rows="(dep)",
                clearWith=list(
                    "group",
                    "group1Level",
                    "group2Level",
                    "nBoot",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Zmienna", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="Statystyka t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ciLowerClass", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpperClass", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Rozk\u0142ad bootstrapowy",
                items="(dep)",
                clearWith=list(
                    "group",
                    "group1Level",
                    "group2Level",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                template=jmvcore::Image$new(
                    options=options,
                    title="Rozk\u0142ad bootstrapowy \u2014 $key",
                    width=500,
                    height=350,
                    renderFun=".plot")))}))

bootTest2Base <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootTest2Base",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootTest2",
                version = c(0,1,0),
                options = options,
                results = bootTest2Results$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowe porownanie dwoch grup
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowy przedzial ufnosci dla roznicy srednich miedzy dwiema niezaleznymi grupami.
#'}
#' @param data .
#' @param dep .
#' @param group .
#' @param group1Level .
#' @param group2Level .
#' @param nBoot .
#' @param ciWidth .
#' @param showClassical .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$testTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$classicalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$testTable$asDF}
#'
#' \code{as.data.frame(results$testTable)}
#'
#' @export
bootTest2 <- function(
    data,
    dep,
    group,
    group1Level,
    group2Level,
    nBoot = 1000,
    ciWidth = 95,
    showClassical = FALSE,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootTest2 requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- bootTest2Options$new(
        dep = dep,
        group = group,
        group1Level = group1Level,
        group2Level = group2Level,
        nBoot = nBoot,
        ciWidth = ciWidth,
        showClassical = showClassical,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootTest2Class$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

