
# This file is automatically generated, you probably don't want to edit this

bootPropOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootPropOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            nBoot = 1000,
            ciWidth = 95,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootProp",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..var)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        var = function() private$..var$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..var = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootPropResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootPropResults",
    inherit = jmvcore::Group,
    active = list(
        propTable = function() private$.items[["propTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowy przedzial ufnosci dla proporcji")
            self$add(jmvcore::Table$new(
                options=options,
                name="propTable",
                title="Bootstrapowe przedzia\u0142y ufno\u015Bci dla proporcji",
                clearWith=list(
                    "var",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="level", 
                        `title`="Poziom", 
                        `type`="text"),
                    list(
                        `name`="count", 
                        `title`="Liczebno\u015B\u0107", 
                        `type`="integer"),
                    list(
                        `name`="prop", 
                        `title`="Proporcja", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Rozk\u0142ady bootstrapowe",
                clearWith=list(
                    "var",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                template=jmvcore::Image$new(
                    options=options,
                    title="Rozk\u0142ad bootstrapowy \u2014 $key",
                    width=500,
                    height=350,
                    renderFun=".plot")))}))

bootPropBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootPropBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootProp",
                version = c(0,1,0),
                options = options,
                results = bootPropResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowy przedzial ufnosci dla proporcji
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowy przedzial ufnosci dla proporcji.
#'}
#' @param data .
#' @param var .
#' @param nBoot .
#' @param ciWidth .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$propTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$propTable$asDF}
#'
#' \code{as.data.frame(results$propTable)}
#'
#' @export
bootProp <- function(
    data,
    var,
    nBoot = 1000,
    ciWidth = 95,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootProp requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL))


    options <- bootPropOptions$new(
        var = var,
        nBoot = nBoot,
        ciWidth = ciWidth,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootPropClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

