
# This file is automatically generated, you probably don't want to edit this

bootMultiGroupOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootMultiGroupOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            nBoot = 1000,
            ciWidth = 95,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootMultiGroup",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootMultiGroupResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootMultiGroupResults",
    inherit = jmvcore::Group,
    active = list(
        groupTable = function() private$.items[["groupTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowe PU per grupa")
            self$add(jmvcore::Table$new(
                options=options,
                name="groupTable",
                title="Bootstrapowe przedzia\u0142y ufno\u015Bci per grupa",
                clearWith=list(
                    "dep",
                    "group",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Zmienna", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="group", 
                        `title`="Grupa", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="\u015Arednia", 
                        `type`="number"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Rozk\u0142ady bootstrapowe",
                items="(dep)",
                clearWith=list(
                    "dep",
                    "group",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                template=jmvcore::Image$new(
                    options=options,
                    title="Rozk\u0142ad bootstrapowy \u2014 $key",
                    width=500,
                    height=350,
                    renderFun=".plot")))}))

bootMultiGroupBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootMultiGroupBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootMultiGroup",
                version = c(0,1,0),
                options = options,
                results = bootMultiGroupResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowe PU per grupa
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowe przedzialy ufnosci dla srednich w wielu grupach.
#'}
#' @param data .
#' @param dep .
#' @param group .
#' @param nBoot .
#' @param ciWidth .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$groupTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$groupTable$asDF}
#'
#' \code{as.data.frame(results$groupTable)}
#'
#' @export
bootMultiGroup <- function(
    data,
    dep,
    group,
    nBoot = 1000,
    ciWidth = 95,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootMultiGroup requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- bootMultiGroupOptions$new(
        dep = dep,
        group = group,
        nBoot = nBoot,
        ciWidth = ciWidth,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootMultiGroupClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

