
# This file is automatically generated, you probably don't want to edit this

bootExploreOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootExploreOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            nBoot = 10,
            ciWidth = 95,
            seed = 42, ...) {

            super$initialize(
                package="jboot",
                name="bootExplore",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=10,
                min=1,
                max=50)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42,
                min=1,
                max=999999)

            self$.addOption(private$..dep)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
        }),
    active = list(
        dep = function() private$..dep$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value),
    private = list(
        ..dep = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..seed = NA)
)

bootExploreResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootExploreResults",
    inherit = jmvcore::Group,
    active = list(
        origTable = function() private$.items[["origTable"]],
        samplesTable = function() private$.items[["samplesTable"]],
        summaryTable = function() private$.items[["summaryTable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Eksploracja bootstrapu krok po kroku")
            self$add(jmvcore::Table$new(
                options=options,
                name="origTable",
                title="Dane oryginalne \u2014 podsumowanie",
                clearWith=list(
                    "dep"),
                columns=list(
                    list(
                        `name`="stat", 
                        `title`="Statystyka", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Warto\u015B\u0107", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="samplesTable",
                title="Pr\u00F3by bootstrapowe",
                clearWith=list(
                    "dep",
                    "nBoot",
                    "seed"),
                columns=list(
                    list(
                        `name`="sample", 
                        `title`="Nr pr\u00F3by", 
                        `type`="integer"),
                    list(
                        `name`="indices", 
                        `title`="Wylosowane indeksy", 
                        `type`="text"),
                    list(
                        `name`="values", 
                        `title`="Wylosowane warto\u015Bci", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="\u015Arednia", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="Podsumowanie bootstrapu",
                clearWith=list(
                    "dep",
                    "nBoot",
                    "seed",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="stat", 
                        `title`="Statystyka", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Warto\u015B\u0107", 
                        `type`="number"))))}))

bootExploreBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootExploreBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootExplore",
                version = c(0,1,0),
                options = options,
                results = bootExploreResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Eksploracja bootstrapu krok po kroku
#'
#' 
#'
#' @examples
#' \donttest{
#' Krokowa eksploracja procesu bootstrapu dla celow dydaktycznych.
#'}
#' @param data .
#' @param dep .
#' @param nBoot .
#' @param ciWidth .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$origTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$samplesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$origTable$asDF}
#'
#' \code{as.data.frame(results$origTable)}
#'
#' @export
bootExplore <- function(
    data,
    dep,
    nBoot = 10,
    ciWidth = 95,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootExplore requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- bootExploreOptions$new(
        dep = dep,
        nBoot = nBoot,
        ciWidth = ciWidth,
        seed = seed)

    analysis <- bootExploreClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

