
# This file is automatically generated, you probably don't want to edit this

bootConvergenceOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootConvergenceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            ciWidth = 95,
            seed = 42, ...) {

            super$initialize(
                package="jboot",
                name="bootConvergence",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=42,
                min=1,
                max=999999)

            self$.addOption(private$..dep)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
        }),
    active = list(
        dep = function() private$..dep$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value),
    private = list(
        ..dep = NA,
        ..ciWidth = NA,
        ..seed = NA)
)

bootConvergenceResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootConvergenceResults",
    inherit = jmvcore::Group,
    active = list(
        convTable = function() private$.items[["convTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Zbieznosc bootstrapu")
            self$add(jmvcore::Table$new(
                options=options,
                name="convTable",
                title="Wp\u0142yw liczby B na przedzia\u0142 ufno\u015Bci",
                clearWith=list(
                    "dep",
                    "ciWidth",
                    "seed"),
                columns=list(
                    list(
                        `name`="b", 
                        `title`="B", 
                        `type`="integer"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciWidth", 
                        `title`="Szeroko\u015B\u0107 PU", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plots",
                title="Zbie\u017Cno\u015B\u0107 przedzia\u0142u ufno\u015Bci",
                width=550,
                height=400,
                clearWith=list(
                    "dep",
                    "ciWidth",
                    "seed"),
                renderFun=".plot"))}))

bootConvergenceBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootConvergenceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootConvergence",
                version = c(0,1,0),
                options = options,
                results = bootConvergenceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Zbieznosc bootstrapu
#'
#' 
#'
#' @examples
#' \donttest{
#' Analiza wplywu liczby prob bootstrapowych (B) na stabilnosc wynikow.
#'}
#' @param data .
#' @param dep .
#' @param ciWidth .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$convTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$convTable$asDF}
#'
#' \code{as.data.frame(results$convTable)}
#'
#' @export
bootConvergence <- function(
    data,
    dep,
    ciWidth = 95,
    seed = 42) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootConvergence requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- bootConvergenceOptions$new(
        dep = dep,
        ciWidth = ciWidth,
        seed = seed)

    analysis <- bootConvergenceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

