
# This file is automatically generated, you probably don't want to edit this

bootMedianOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootMedianOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            nBoot = 1000,
            ciWidth = 95,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootMedian",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariables$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..dep)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        dep = function() private$..dep$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..dep = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootMedianResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootMedianResults",
    inherit = jmvcore::Group,
    active = list(
        medianTable = function() private$.items[["medianTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowy PU dla mediany")
            self$add(jmvcore::Table$new(
                options=options,
                name="medianTable",
                title="Bootstrapowy przedzia\u0142 ufno\u015Bci dla mediany",
                rows="(dep)",
                clearWith=list(
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Zmienna", 
                        `type`="text"),
                    list(
                        `name`="median", 
                        `title`="Mediana", 
                        `type`="number"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Rozk\u0142ad bootstrapowy",
                items="(dep)",
                clearWith=list(
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                template=jmvcore::Image$new(
                    options=options,
                    title="Rozk\u0142ad bootstrapowy \u2014 $key",
                    width=500,
                    height=350,
                    renderFun=".plot")))}))

bootMedianBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootMedianBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootMedian",
                version = c(0,1,0),
                options = options,
                results = bootMedianResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowy PU dla mediany
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowy przedzial ufnosci dla mediany.
#'}
#' @param data .
#' @param dep .
#' @param nBoot .
#' @param ciWidth .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$medianTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$medianTable$asDF}
#'
#' \code{as.data.frame(results$medianTable)}
#'
#' @export
bootMedian <- function(
    data,
    dep,
    nBoot = 1000,
    ciWidth = 95,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootMedian requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- bootMedianOptions$new(
        dep = dep,
        nBoot = nBoot,
        ciWidth = ciWidth,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootMedianClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

