
# This file is automatically generated, you probably don't want to edit this

bootCorrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootCorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            nBoot = 1000,
            ciWidth = 95,
            method = "pearson",
            showClassical = FALSE,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootCorr",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "pearson",
                    "spearman"),
                default="pearson")
            private$..showClassical <- jmvcore::OptionBool$new(
                "showClassical",
                showClassical,
                default=FALSE)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..vars)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..method)
            self$.addOption(private$..showClassical)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        vars = function() private$..vars$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        method = function() private$..method$value,
        showClassical = function() private$..showClassical$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..vars = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..method = NA,
        ..showClassical = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootCorrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootCorrResults",
    inherit = jmvcore::Group,
    active = list(
        corrTable = function() private$.items[["corrTable"]],
        classicalTable = function() private$.items[["classicalTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowy przedzial ufnosci dla korelacji")
            self$add(jmvcore::Table$new(
                options=options,
                name="corrTable",
                title="Bootstrapowe przedzia\u0142y ufno\u015Bci dla korelacji",
                clearWith=list(
                    "vars",
                    "nBoot",
                    "ciWidth",
                    "method",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Zmienna 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Zmienna 2", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `title`="Korelacja", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="classicalTable",
                title="Test klasyczny (test korelacji)",
                visible="(showClassical)",
                clearWith=list(
                    "vars",
                    "nBoot",
                    "ciWidth",
                    "method"),
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Zmienna 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Zmienna 2", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `title`="Korelacja", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="t", 
                        `title`="Statystyka t", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ciLowerClass", 
                        `title`="Dolna granica PU", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ciUpperClass", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Rozk\u0142ady bootstrapowe",
                clearWith=list(
                    "vars",
                    "nBoot",
                    "ciWidth",
                    "method",
                    "seed",
                    "ciMethod"),
                template=jmvcore::Image$new(
                    options=options,
                    title="Rozk\u0142ad bootstrapowy \u2014 $key",
                    width=500,
                    height=350,
                    renderFun=".plot")))}))

bootCorrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootCorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootCorr",
                version = c(0,1,0),
                options = options,
                results = bootCorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowy przedzial ufnosci dla korelacji
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowy przedzial ufnosci dla korelacji Pearsona lub Spearmana.
#'}
#' @param data .
#' @param vars .
#' @param nBoot .
#' @param ciWidth .
#' @param method .
#' @param showClassical .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$corrTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$classicalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$corrTable$asDF}
#'
#' \code{as.data.frame(results$corrTable)}
#'
#' @export
bootCorr <- function(
    data,
    vars,
    nBoot = 1000,
    ciWidth = 95,
    method = "pearson",
    showClassical = FALSE,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootCorr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- bootCorrOptions$new(
        vars = vars,
        nBoot = nBoot,
        ciWidth = ciWidth,
        method = method,
        showClassical = showClassical,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootCorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

