
# This file is automatically generated, you probably don't want to edit this

bootRegressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootRegressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            pred = NULL,
            nBoot = 1000,
            ciWidth = 95,
            seed = 0,
            ciMethod = "perc", ...) {

            super$initialize(
                package="jboot",
                name="bootRegression",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..pred <- jmvcore::OptionVariable$new(
                "pred",
                pred,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nBoot <- jmvcore::OptionInteger$new(
                "nBoot",
                nBoot,
                default=1000,
                min=100,
                max=100000)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.9)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0,
                max=999999)
            private$..ciMethod <- jmvcore::OptionList$new(
                "ciMethod",
                ciMethod,
                options=list(
                    "perc",
                    "bca",
                    "basic"),
                default="perc")

            self$.addOption(private$..dep)
            self$.addOption(private$..pred)
            self$.addOption(private$..nBoot)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..seed)
            self$.addOption(private$..ciMethod)
        }),
    active = list(
        dep = function() private$..dep$value,
        pred = function() private$..pred$value,
        nBoot = function() private$..nBoot$value,
        ciWidth = function() private$..ciWidth$value,
        seed = function() private$..seed$value,
        ciMethod = function() private$..ciMethod$value),
    private = list(
        ..dep = NA,
        ..pred = NA,
        ..nBoot = NA,
        ..ciWidth = NA,
        ..seed = NA,
        ..ciMethod = NA)
)

bootRegressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootRegressionResults",
    inherit = jmvcore::Group,
    active = list(
        coefTable = function() private$.items[["coefTable"]],
        fitTable = function() private$.items[["fitTable"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bootstrapowy PU dla wspolczynnika regresji")
            self$add(jmvcore::Table$new(
                options=options,
                name="coefTable",
                title="Bootstrapowy PU dla wsp\u00F3\u0142czynnik\u00F3w regresji",
                clearWith=list(
                    "dep",
                    "pred",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Sk\u0142adnik", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estymacja", 
                        `type`="number"),
                    list(
                        `name`="seBoot", 
                        `title`="B\u0142\u0105d std. bootstrap", 
                        `type`="number"),
                    list(
                        `name`="ciLower", 
                        `title`="Dolna granica PU", 
                        `type`="number"),
                    list(
                        `name`="ciUpper", 
                        `title`="G\u00F3rna granica PU", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="fitTable",
                title="Dopasowanie modelu",
                clearWith=list(
                    "dep",
                    "pred"),
                columns=list(
                    list(
                        `name`="stat", 
                        `title`="Statystyka", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Warto\u015B\u0107", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plots",
                title="Rozk\u0142ad bootstrapowy",
                width=500,
                height=350,
                clearWith=list(
                    "dep",
                    "pred",
                    "nBoot",
                    "ciWidth",
                    "seed",
                    "ciMethod"),
                renderFun=".plot"))}))

bootRegressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bootRegressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jboot",
                name = "bootRegression",
                version = c(0,1,0),
                options = options,
                results = bootRegressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Bootstrapowy PU dla wspolczynnika regresji
#'
#' 
#'
#' @examples
#' \donttest{
#' Bootstrapowy przedzial ufnosci dla wspolczynnika regresji liniowej.
#'}
#' @param data .
#' @param dep .
#' @param pred .
#' @param nBoot .
#' @param ciWidth .
#' @param seed .
#' @param ciMethod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$coefTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coefTable$asDF}
#'
#' \code{as.data.frame(results$coefTable)}
#'
#' @export
bootRegression <- function(
    data,
    dep,
    pred,
    nBoot = 1000,
    ciWidth = 95,
    seed = 0,
    ciMethod = "perc") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bootRegression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(pred)) pred <- jmvcore::resolveQuo(jmvcore::enquo(pred))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(pred), pred, NULL))


    options <- bootRegressionOptions$new(
        dep = dep,
        pred = pred,
        nBoot = nBoot,
        ciWidth = ciWidth,
        seed = seed,
        ciMethod = ciMethod)

    analysis <- bootRegressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

