test_that("t tests match stats::t.test and d intervals are sane", {
    x <- sleep$extra[sleep$group == 1]; y <- sleep$extra[sleep$group == 2]
    one <- oneSampleT(x, 0)
    ref <- t.test(x)
    expect_equal(one$stat, unname(ref$statistic)); expect_equal(one$p, ref$p.value)
    expect_equal(c(one$lower, one$upper), as.numeric(ref$conf.int))
    expect_true(one$esLower < one$es && one$es < one$esUpper)
    g <- factor(rep(c("a", "b"), each = 10)); yy <- c(x, y)
    two <- twoSampleT(yy, g, welch = TRUE)
    ref2 <- t.test(x, y)
    expect_equal(two$stat, unname(ref2$statistic)); expect_equal(two$df, unname(ref2$parameter))
    twoS <- twoSampleT(yy, g, welch = FALSE)
    expect_equal(twoS$df, 18)
    expect_equal(twoS$es, (mean(x) - mean(y)) / sqrt((var(x) + var(y)) / 2))
    mw <- mannWhitney(yy, g)
    expect_equal(mw$p, wilcox.test(x, y, exact = FALSE)$p.value)
    expect_equal(mw$es, 1 - 2 * unname(wilcox.test(x, y, exact = FALSE)$statistic) / 100)
})

test_that("one-sided hypotheses and sign/permutation/bootstrap helpers", {
    x <- c(1.2, 0.8, 2.1, 1.7, 0.3, 1.1, 2.4, 0.9)
    expect_equal(oneSampleT(x, 0, "greater")$p, t.test(x, alternative = "greater")$p.value)
    expect_equal(signTest(x, 0)$p, binom.test(8, 8)$p.value)
    pm <- permOne(x, 0, B = 500); expect_true(pm$p > 0 && pm$p <= 1)
    bt <- bootOne(x, B = 500); expect_true(bt$lower < mean(x) && mean(x) < bt$upper)
    d <- dInterval(0.5, 20, 20); expect_true(d[1] < 0.5 && d[2] > 0.5)
    d0 <- dInterval(0, 30); expect_equal(mean(d0), 0, tolerance = 1e-3)
})
