test_that("pairwise observations use one complete-case sample for every result", {
    x <- c(-2, -1, 0, 1, 2, NA, 100)
    y <- c(-1, 1, 0, 2, 1, 5, NA)
    r <- measurementEllipse(x, y)
    expect_equal(r$n, 5L)
    expect_equal(r$missing, 2L)
    expect_equal(r$covariance, cov(cbind(x = x[1:5], y = y[1:5])))
    expect_equal(r$meanCovariance, r$covariance / 5)
    expect_equal(r$r, cor(x[1:5], y[1:5]))
    expect_equal(sum(r$principal$share), 100)
    expect_equal(r$center, c(x = 0, y = 0.6))
})

test_that("rotated ellipse has known eigenvalues and orientation", {
    # Four centered observations with sample eigenvalues exactly 9 and 1.
    z <- rbind(c(sqrt(13.5), 0), c(-sqrt(13.5), 0), c(0, sqrt(1.5)), c(0, -sqrt(1.5)))
    angle <- pi / 6
    rotation <- matrix(c(cos(angle), sin(angle), -sin(angle), cos(angle)), 2)
    xy <- sweep(z %*% t(rotation), 2, c(10, -5), "+")
    r <- measurementEllipse(xy[, 1], xy[, 2])
    expect_equal(r$principal$eigenvalue, c(9, 1))
    expect_equal(r$radii, c(3, 1))
    expect_equal(r$angle, 30)
    expect_equal(r$principal$angle[2], 120)
    expect_equal(r$principal$share, c(90, 10))
    centered <- sweep(as.matrix(r$points), 2, r$center, "-")
    expect_equal(rowSums((centered %*% solve(r$covariance)) * centered), rep(1, 361), tolerance = 1e-10)
    expect_equal(as.numeric(r$points[1, ]), as.numeric(r$points[361, ]))
    scaled <- measurementEllipse(1000 * xy[, 1], 1000 * xy[, 2])
    expect_equal(scaled$radii, 1000 * r$radii)
    expect_equal(scaled$angle, r$angle)
    expect_equal(scaled$covariance, 1e6 * r$covariance)
})

test_that("normal scatter and Hotelling mean confidence have distinct scaling", {
    x <- c(-3, -1, 0, 1, 3, 2)
    y <- c(0, -2, 1, 2, 1, -1)
    unit <- measurementEllipse(x, y)
    scatter <- measurementEllipse(x, y, "scatter", 95)
    mean <- measurementEllipse(x, y, "mean", 95)
    expect_equal(scatter$radii / unit$radii, rep(sqrt(qchisq(.95, 2)), 2))
    expect_equal(mean$radii / unit$radii, rep(sqrt(2 * 5 / (6 * 4) * qf(.95, 2, 4)), 2))
    # Every confidence-boundary point must satisfy the Hotelling T-squared cutoff.
    centered <- sweep(as.matrix(mean$points), 2, mean$center, "-")
    t2 <- 6 * rowSums((centered %*% solve(mean$covariance)) * centered)
    expect_equal(t2, rep(2 * 5 / 4 * qf(.95, 2, 4), 361), tolerance = 1e-10)
    expect_gt(measurementEllipse(x, y, "mean", 99)$radii[1], mean$radii[1])
    expect_equal(measurementEllipse(x, y, "standard", 99)$radii, unit$radii)
})

test_that("singular data keep descriptive results without claiming 2D confidence", {
    line <- measurementEllipse(1:5, 2 * (1:5))
    expect_true(line$available)
    expect_equal(line$radii[2], 0, tolerance = 1e-7)
    expect_equal(line$angle, atan(2) * 180 / pi)
    expect_false(measurementEllipse(1:5, 2 * (1:5), "mean")$available)
    expect_false(measurementEllipse(c(1, 2), c(2, 1), "mean")$available)
    point <- measurementEllipse(rep(1, 4), rep(2, 4))
    expect_equal(point$radii, c(0, 0))
    expect_true(is.na(point$r))
    expect_true(is.na(point$angle))
    circle <- measurementEllipse(c(-1, 1, 0, 0), c(0, 0, -1, 1))
    expect_true(is.na(circle$angle))
    expect_equal(circle$radii[1], circle$radii[2])
    expect_true(all(is.na(point$principal$share)))
    expect_error(measurementEllipse(c(NA_real_, 1), c(1, 1)), "dwie kompletne")
    expect_error(measurementEllipse(c(1, Inf), c(1, 2)), "nieskończoności")
    expect_error(measurementEllipse(1:3, 1:2), "długości")
    expect_error(measurementEllipse(1:3, 1:3, level = 100), "Poziom")
})

test_that("compiled ellipse analysis connects options, tables and plots", {
    skip_if_not_installed("jPomiar")
    d <- data.frame(east = c(-3, -1, 0, 1, 3, 2), north = c(0, -2, 1, 2, 1, -1))
    r <- jPomiar:::elipsa(data = d, x = "east", y = "north", ellipseType = "mean",
                         showPlot = TRUE, showAxes = TRUE)
    expect_equal(r$summary$asDF$n, 6L)
    expect_equal(r$covariance$asDF$x, as.numeric(cov(d)[, 1]))
    expect_equal(r$meanCovariance$asDF$y, as.numeric(cov(d)[, 2]) / 6)
    expect_equal(r$ellipse$asDF$major, measurementEllipse(d$east, d$north, "mean")$radii[1])
    expect_match(r$metody$content, "Hotellinga")
    expect_match(r$metody$content, "„east”")
    expect_true(r$plot$state$showAxes)
    expect_error(jPomiar:::elipsa(data = d, x = "east", y = "east"), "różne kolumny")
    line <- jPomiar:::elipsa(data = data.frame(x = 1:4, y = 1:4), x = "x", y = "y", ellipseType = "mean")
    expect_equal(nrow(line$ellipse$asDF), 0)
    expect_equal(nrow(line$covariance$asDF), 2)
    expect_match(line$ellipse$notes$mean$note, "niedostępny")
    expect_match(line$principal$notes$singular$note, "osobliwa")
    skip_if_not(capabilities("cairo"))
    out <- tempfile(fileext = ".pdf")
    grDevices::cairo_pdf(out)
    on.exit({grDevices::dev.off(); unlink(out)}, add = TRUE)
    expect_true(measurementEllipsePlot(r$plot$state, ggplot2::theme_minimal(), list()))
})
