# Generates data/satelity.csv from the committed CelesTrak TLE snapshot in
# data-raw/tle-2026-08-26/ (see tle-pobierz.R for how the snapshot was made).
# Deterministic: plain fixed-width TLE parsing, no external packages, so the
# CSV can always be regenerated from the snapshot alone.
# Attribution: TLE data generated by USSPACECOM, distributed by CelesTrak
# (https://celestrak.org), snapshot 2026-08-26.

snapshotDir <- "tle-2026-08-26"

konstelacje <- c(
    stations       = "Stacje kosmiczne",
    `gps-ops`      = "GPS",
    `glo-ops`      = "GLONASS",
    galileo        = "Galileo",
    beidou         = "BeiDou",
    `iridium-NEXT` = "Iridium NEXT",
    starlink       = "Starlink",
    oneweb         = "OneWeb",
    weather        = "Meteorologiczne",
    goes           = "Meteorologiczne",
    science        = "Naukowe",
    geo            = "Komunikacyjne GEO"
)

# standard gravitational parameter of Earth [km^3/s^2] and mean radius [km]
mu <- 398600.4418
rZiemi <- 6371

parseGroup <- function(path, konstelacja) {
    lines <- readLines(path, warn = FALSE)
    lines <- lines[nzchar(trimws(lines))]
    n <- length(lines) %/% 3
    if (n == 0)
        return(NULL)
    nazwa <- trimws(lines[seq(1, by = 3, length.out = n)])
    l1 <- lines[seq(2, by = 3, length.out = n)]
    l2 <- lines[seq(3, by = 3, length.out = n)]
    data.frame(
        nazwa = nazwa,
        norad = as.integer(substr(l1, 3, 7)),
        konstelacja = konstelacja,
        inklinacja = as.numeric(substr(l2, 9, 16)),
        # eccentricity has an implied leading decimal point in TLE
        ekscentrycznosc = as.numeric(paste0("0.", substr(l2, 27, 33))),
        obiegi_na_dobe = as.numeric(substr(l2, 53, 63)),
        stringsAsFactors = FALSE
    )
}

d <- do.call(rbind, lapply(names(konstelacje), function(g) {
    parseGroup(file.path(snapshotDir, paste0(g, ".txt")), konstelacje[[g]])
}))

# some satellites appear in more than one CelesTrak group (e.g. GOES in both
# goes and geo) — keep the first occurrence, group order above sets priority
d <- d[!duplicated(d$norad), ]

# semi-major axis from Kepler's third law; altitude above mean Earth radius
nRad <- d$obiegi_na_dobe * 2 * pi / 86400          # mean motion [rad/s]
a <- (mu / nRad^2)^(1 / 3)                          # semi-major axis [km]
d$wysokosc_km <- round(a - rZiemi, 1)
d$okres_min <- round(1440 / d$obiegi_na_dobe, 1)

d$typ_orbity <- ifelse(d$wysokosc_km < 2000, "LEO",
                ifelse(d$wysokosc_km < 34000, "MEO", "GEO"))

d$inklinacja <- round(d$inklinacja, 2)
d$obiegi_na_dobe <- round(d$obiegi_na_dobe, 4)

d <- d[order(d$konstelacja, d$nazwa), ]
write.csv(d, file.path("..", "data", "satelity.csv"),
          row.names = FALSE, quote = TRUE)
cat(sprintf("satelity.csv: %d satelitow, %d konstelacji\n",
            nrow(d), length(unique(d$konstelacja))))
print(table(d$konstelacja))
