# One-off authoring script: downloads TLE sets from CelesTrak and writes the
# curated snapshot committed in data-raw/tle-<date>/. Large constellations are
# subsampled with a fixed seed. The committed snapshot (not this download) is
# the reproducible source for data/satelity.csv — see satelity.R.
# Attribution: TLE data generated by USSPACECOM, distributed by CelesTrak
# (https://celestrak.org). Snapshot date: 2026-08-26.

snapshotDir <- file.path("tle-2026-08-26")
srcDir <- Sys.getenv("TLE_SRC", "tle-download")  # raw downloads (not committed)
dir.create(snapshotDir, showWarnings = FALSE)
dir.create(srcDir, showWarnings = FALSE)

groups <- c("stations", "gps-ops", "glo-ops", "galileo", "beidou",
            "iridium-NEXT", "starlink", "oneweb", "weather", "goes",
            "science", "geo")
# keep = NA -> keep all satellites in the group
keep <- c(stations = NA, `gps-ops` = NA, `glo-ops` = NA, galileo = NA,
          beidou = NA, `iridium-NEXT` = NA, starlink = 80, oneweb = 60,
          weather = NA, goes = NA, science = NA, geo = 60)

readTLEfile <- function(path) {
    lines <- readLines(path, warn = FALSE)
    lines <- lines[nzchar(trimws(lines))]
    n <- length(lines) %/% 3
    lapply(seq_len(n), function(i) lines[(3 * i - 2):(3 * i)])
}

set.seed(2026)
for (g in groups) {
    src <- file.path(srcDir, paste0(g, ".txt"))
    if (!file.exists(src)) {
        url <- sprintf(
            "https://celestrak.org/NORAD/elements/gp.php?GROUP=%s&FORMAT=tle", g)
        download.file(url, src, quiet = TRUE)
        Sys.sleep(1)
    }
    sats <- readTLEfile(src)
    k <- keep[[g]]
    if (!is.na(k) && length(sats) > k)
        sats <- sats[sort(sample(seq_along(sats), k))]
    writeLines(unlist(sats), file.path(snapshotDir, paste0(g, ".txt")))
    cat(sprintf("%s: %d satelitow\n", g, length(sats)))
}
